version: '3'

services:
  redis:
    image: redis
    container_name: logistician_redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - backend

  postgres:
    image: postgis/postgis
    container_name: logistician_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: mydb
    ports:
      - "5432:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./extension.sql:/docker-entrypoint-initdb.d/extension.sql
    networks:
      - backend

  zipkin:
    image: openzipkin/zipkin
    environment:
      - STORAGE_TYPE=mem
    ports:
      - 9411:9411
    networks:
      - backend
  
  rabbitmq:
    image: rabbitmq:management
    container_name: logistician_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:  
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - backend

volumes:
  redis_data:
  postgres_data:
  rabbitmq_data:

networks:
  backend: