version: '3'

services:
  redis:
    image: redis
    container_name: logistician_redis
    ports:
      - "6379:6379"
    networks:
      - backend

  postgres:
    image: postgis/postgis
    container_name: logistician_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: mydb
    ports:
      - "5432:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./extension.sql:/docker-entrypoint-initdb.d/extension.sql
    networks:
      - backend

  zipkin:
    image: openzipkin/zipkin
    environment:
      - STORAGE_TYPE=mem
    ports:
      - 9411:9411
  
  # rabbitmq:
  #   image: rabbitmq
  #   container_name: rtf_rabbitmq
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
  #   environment:
  #     RABBITMQ_DEFAULT_USER: guest
  #     RABBITMQ_DEFAULT_PASS: guest
  #   networks:
  #     - app_network

volumes:
  postgres_data:

networks:
  backend: