export enum UserErrorCode {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  EMAIL_VERIFICATION_CODE_NOT_FOUND = 'EMAIL_VERIFICATION_CODE_NOT_FOUND',
  INVALID_EMAIL_VERIFICATION_CODE = 'INVALID_EMAIL_VERIFICATION_CODE',
  ACCOUNT_NOT_ACTIVATED = 'ACCOUNT_NOT_ACTIVATED',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  IMPOSSIBLE_OPERATION = 'IMPOSSIBLE_OPERATION',
  BALANCE_NOT_FOUND = 'BALANCE_NOT_FOUND',
  INFFICIENT_FUNDS = 'INFFICIENT_FUNDS',
}
