apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: logistician-app-ingress
  namespace: logistician-app
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/server-snippets: |
      location / {
        proxysetheader Upgrade $httpupgrade;
        proxyhttpversion 1.1;
        proxysetheader X-Forwarded-Host $httphost;
        proxysetheader X-Forwarded-Proto $scheme;
        proxysetheader X-Forwarded-For $remoteaddr;
        proxysetheader Host $host;
        proxysetheader Connection "upgrade";
        proxycachebypass $httpupgrade;
      }
spec:
  ingressClassName: "nginx"
  rules:
    - host: localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: logistician-app-service
                port:
                  number: 3000
          # - path: /ws
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: logistician-app-service
          #       port:
          #         number: 3010
          # - path: /infrastructure/rabbitmq
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: rabbitmq-service
          #       port:
          #         number: 15672
          # - path: /infrastructure/zipkin
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: zipkin-service
          #       port:
          #         number: 9411